OPENAI_API_KEY = "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"
REPLICATE_API_TOKEN = "r8_3js0xfv2tXTIHkJYDl7sQTgXXnXKvBM28jBfZ"
PUSHBULLET_API_KEY = "o.22D73CVRXZ0pQQhDKNdfIaK7qVID5940"
TWILIO = "BX39JKVMDJ8MCPM1LSNQNCAT"